### ISSUE TITLE
Library not working in Safari

### ISSUE THREAD

**Issue by wwwonka** [konstantin-lukas/intl-currency-input#2]
Hi.
The library works great in Firefox and Chrome. I have not been experiencing any problems outside of Safari both on macOS (Mojave 10.14.6) and iOS 13. Basically the text input wont display as expected, with the seperators and currency symbols.

The console logs this error:
`TypeError: Failed to initialize NumberFormat since used feature is not supported in the linked ICU version`
`
Any idea wether if this can be solved with a polyfill or a part of the library should be rewritten?

Remark: I am using Safari version 14.1.2 on the mac.

**Comment by konstantin-lukas** [comment]
Hi, I was actually thinking about reworking some of the inner workings of this library. I'm not sure though if what I'm intending to do anyways would fix this issue. Could you maybe tell me if the error references a specific line of code and maybe also send a screenshot of what it looks like vs what it should look like? Thank you!

**Comment by wwwonka** [comment]
Sure.
My code is super basic. All of it is here:

  ```

    const input = 'input';
    const options = {
        currency: 'CAD',
        currencyDisplay: 'none'
    }

    const cinput = new CurrencyInput(input, options);

```

Here is a screenshot, as you can see, the formatting does not occur in Safari (on the right):
<img width="1680" alt="Capture d’écran, le 2021-11-02 à 14 36 30" src="https://user-images.githubusercontent.com/16738328/139924906-441653b6-8e0f-4d50-b32c-d842b9e4c32f.png">

**Comment by konstantin-lukas** [comment]
In theory at least your version of Safari should support the Intl.NumberFormat class according to caniuse.com
Sounds like a Safari issue. The Intl.NumberFormat is only used once in the entire class so perhaps I can replace it with something else in the next update. I'll put it on my to-do and see what I can do. This whole library is based on the Intl class. So in theory support for this library goes as far as the support for the Intl class and all of it's features (which covers quite a lot of systems and browser cause it's built into JavaScript) which allows the library to be quite small. But of course I'll try to fix it if it is something that can be fixed by me.

**Comment by wwwonka** [comment]
Hey. I found a solution inspired by [this thread](https://github.com/Financial-Times/polyfill-library/issues/886).

Basically on line 163:

```
 getCurrencyDecimalCount() {
        const decimalTest = new Intl.NumberFormat({ style: 'currency', currency: this.currency, signDisplay: 'never', currencyDisplay: 'code' }).format(1).substr(4);
        return (decimalTest.match(/(0)/g) || []).length;
    }
```

I just removed the `"en"` argument, and it now works everywhere, even in Safari. When this argument is not provided, it defaults to `"en"` anyways, they say.

I hope this helps you.

**Comment by konstantin-lukas** [comment]
Interesting, but I think it defaults to the runtime's locale. Can you try and see if changing 'en' to 'en-US' also fixes this issue? If so, I think that would be a more stable fix for this issue.

**Comment by konstantin-lukas** [comment]
Version 2.0.0 shouldn't have this bug.
