### ISSUE TITLE
Where can I get the script to use it offline?

### ISSUE THREAD

**Issue by curiosport** [konstantin-lukas/intl-currency-input#8]
I can't see how by following that CDN I can find the "**intl-currency-input.js**" file, or how this works?
```
<script type="module">
  import intlCurrencyInput from 'https://cdn.skypack.dev/intl-currency-input';
</script>
```
I should be able to use it offline if possible.

**Comment by konstantin-lukas** [comment]
Well CDNs are quite the opposite of offline usage and also 2 other things to consider:
1. you can't use import syntax with cdn links
2. I didn't update the cdn link for version 2.0.0

If you are unfamiliar with how building JavaScript apps works, I recommend reading into it but basically you use a package manager like npm to create a package in which you can install other packages as dependencies. Then you run `npm install intl-currency-input ` to install this lib as a dependency. Then you can use `import IntlCurrencyInput from 'intl-currency-input` in your javascript files. But you can't just run js files with import statements. What you need to do instead is use a bundler like rollup or Webpack to "squish" your source code together. This basically resolves these import statements and makes using libraries possible. This bundling process is also independent from any CDNs so you can use it offline. CDNs are basically for when you don't want to ship your app with a dependency and instead want to fetch it from another server. The JavaScript ecosystem isn't very user friendly in my opinion and it can be difficult to understand how to use libraries but I definitely recommend reading up on that.

**Comment by curiosport** [comment]
What I mean is that I want to do this and nothing more, this is a single input:
`<script src="/static/intl-currency-input.js"></script>`

I don't use node.js neither for development nor for the execution of any javascript package in production, because node.js consumes too many resources, too much, even so I already tried to compile with node.js and create a simple .js and it was not possible for me to achieve it.

**Comment by konstantin-lukas** [comment]
Given that the library defines exports, you can't just compile it. I also don't understand what you mean that you used node.js to compile it because node is a runtime, not a compiler. More importantly, you have to use a bundler to combine the source files together. There was something similar in the webpack config of version 1.X.X of this library but I took that out because it was super janky and inconvenient to use. But in theory I think you can achieve what you want with webpack. Check out their documentation. I think there is a way to put exports into a global variable instead of into a module. I think that way you could use it in HTML script tags like that.
